force-app/main/default/objects/CustomRating_Global_Setting__c/CustomRating_Global_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Global Setting</label>
</CustomObject>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Use_RollupBatch_for_Rollup_Field__c.field-meta.xml
<CustomField>
    <fullName>Use_RollupBatch_for_Rollup_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Make this field True to use other custom settings or False to use the values in the rating rollup field.</inlineHelpText>
    <label>Use RollupBatch for Rollup Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomRating_Scheduler.cls
/**********************************************************************************************************
* Class Name: CustomRating_Scheduler
* Author: KGS
*
* ============================================================================================================
* ============================================================================================================
* Purpose: This class schedule the CustomRating_Batch and CustomRating_RollupBatch based on custom setting.
* ============================================================================================================
* ============================================================================================================
* History:
* VERSION     DATE                  INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0         08-November-2021      KGS           Initial Development
***********************************************************************************************************/
global class CustomRating_Scheduler implements Schedulable{
    global void execute(SchedulableContext sc){        
        
        CustomRating_Global_Setting__c globalSettingObj = CustomRating_Utility.getCustomRatingGlobalSetting();
        
        // If Use_RollupBatch_for_Rollup_Field checkbox is true then execute the CustomRating_RollupBatch.
        if(globalSettingObj.Use_RollupBatch_for_Rollup_Field__c == true){
            Database.executeBatch(new CustomRating_RollupBatch(), 200);
        }else{
             // Enqueue the job to run CustomRating_Queueable class if Use_RollupBatch_for_Rollup_Field is false in custom setting
            System.enqueueJob(new CustomRating_Queueable(0));
        }
    }
}