force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/Custom_Rating_Rollup_Batch_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Rollup Batch Settings</label>
</CustomObject>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Aggregate_Result_Field__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Result_Field__c</fullName>
    <inlineHelpText>This value is the API name of the field used for determining the rating values applied to the custom rating field specified in the object in the global settings above. Values in this field are used as-is if &quot;Use Rollup Batch for Rollup Field&quot; is unchecked in Global Settings.Or if that custom setting is checked this field is populated with values by an additional batch process in the application that runs first to set the values as per the logic in these Rollup Batch Settings.Can be a single std/Cust field</inlineHelpText>
    <label>Aggregate Result Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>Value is the API name of the custom rating object specified in Global Settings the the primary batch process is updating the values and applying the rating per the logic specified in that custom settings. Can be a single standard or custom object. i.e. Account or Project__c</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the API name of the field on the child object that is the standard or custom lookup or master-detail field relating it to the parent object. i.e. AccountId or Account__c</inlineHelpText>
    <label>Relationship Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Relationship_field_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field_Criteria__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the SOQL query criteria used to determine what parent object records should be updated by the rollup batch process. Can be the same as the Global Settings Rating Criteria or a different set of parent records as required. i.e. Type !=&apos;Prospect&apos; AND RecordType.Name = &apos;Customer&apos;</inlineHelpText>
    <label>Relationship Field Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/CustomRating_Global_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Global Setting</label>
</CustomObject>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Use_RollupBatch_for_Rollup_Field__c.field-meta.xml
<CustomField>
    <fullName>Use_RollupBatch_for_Rollup_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Make this field True to use other custom settings or False to use the values in the rating rollup field.</inlineHelpText>
    <label>Use RollupBatch for Rollup Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomRating_RollupBatch.cls
/**********************************************************************************************************
* Class Name: CustomRating_RollupBatch
* Author: KGS
*
* ============================================================================================================
* ============================================================================================================
* Purpose: This batch class is used for field rollup of child records based on custom setting input.
* ============================================================================================================
* ============================================================================================================
* History:
* VERSION     DATE                  INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0         01-November-2021      KGS           Initial Development
***********************************************************************************************************/
global class CustomRating_RollupBatch implements Database.Batchable<sObject>, database.stateful{
    
    public String query = '';
    Custom_Rating_Rollup_Batch_Settings__c customRatingSetting = Custom_Rating_Rollup_Batch_Settings__c.getInstance();
    CustomRating_Global_Setting__c globalSettingObj = CustomRating_Utility.getCustomRatingGlobalSetting();
    
    public string childRelationshipName = CustomRating_Utility.getChildRelationshipName(customRatingSetting);
    
    // Collect the batches of records or objects to be passed to execute
    global Database.QueryLocator start(Database.BatchableContext BC){
        try{
            
            if(customRatingSetting != null){
                
                query +=  CustomRating_Utility.SELECT_STR;
                query +=  customRatingSetting.Aggregate_Result_Field__c;
                query +=  CustomRating_Utility.FROM_STR;
                query +=  customRatingSetting.Parent_Object__c ;
                
                if(customRatingSetting.Relationship_Field_Criteria__c != null 
                  && String.isNotBlank(customRatingSetting.Relationship_Field_Criteria__c))
                {
                    query += ' WHERE ' + customRatingSetting.Relationship_Field_Criteria__c;
                }
                system.debug('query==>'+query);
            }
        } catch(Exception ex){
            system.debug('Exception ->'+ ex.getMessage());
        }
        return Database.getQueryLocator(query);
    }
    
    // Process each batch of records.
    global void execute(Database.BatchableContext BC, List<sObject> sObjectList){
        // This set holds the value of Parent Id.
        Set<String> parentIdSet = new Set<String>();
        
        // This map hold the parent Id and count of child records.
        Map<String,Integer> parentIdVsChildCountMap = new Map<String,Integer>();
        
        // This map updates the count on Parent Object.
        Map<Id,sObject> sObjMap = new Map<Id,sObject>();
        
        for(sObject parentObj : sObjectList){
            parentIdSet.add(parentObj.Id); 
        }
        
        List<AggregateResult> childSobjList = CustomRating_Utility.fetchChildObjectCounts(customRatingSetting,parentIdSet);
        for(AggregateResult arrObj : childSobjList){
            parentIdVsChildCountMap.put(String.valueof(arrObj.get(customRatingSetting.Relationship_Field__c)), Integer.valueof(arrObj.get('expr0')));
        }
        
        for(sObject obj :sObjectList){
            // Create the object based on Id.
            sObject sObj = obj.Id.getSobjectType().newSObject(obj.Id);
            if(parentIdVsChildCountMap.containskey(obj.Id)){
                sObj.Put(customRatingSetting.Aggregate_Result_Field__c,parentIdVsChildCountMap.get(obj.Id));                
            }else{
                sObj.Put(customRatingSetting.Aggregate_Result_Field__c,0);
            }
            sObjMap.put(obj.Id,sObj);               
        }
        
        // Update the values
        if(!sObjMap.isEmpty()){
            Update sObjMap.values(); 
        }         
    }
    
    // Execute any post-processing operations
    global void finish(Database.BatchableContext BC){
        // Enqueue the job to run CustomRating_Batch if Use_RollupBatch_for_Rollup_Field__c is true
        if(globalSettingObj.Use_RollupBatch_for_Rollup_Field__c == true){
            System.enqueueJob(new CustomRating_Queueable(0));
        }
    }  
}