force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/Custom_Rating_Rollup_Batch_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Rollup Batch Settings</label>
</CustomObject>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Aggregate_Result_Field__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Result_Field__c</fullName>
    <inlineHelpText>This value is the API name of the field used for determining the rating values applied to the custom rating field specified in the object in the global settings above. Values in this field are used as-is if &quot;Use Rollup Batch for Rollup Field&quot; is unchecked in Global Settings.Or if that custom setting is checked this field is populated with values by an additional batch process in the application that runs first to set the values as per the logic in these Rollup Batch Settings.Can be a single std/Cust field</inlineHelpText>
    <label>Aggregate Result Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the API name of the object where Rollup values are pulled from. Can also be the same as the Parent Object or another standard or custom object related to the Parent Object. i.e. Opportunity or Project__c</inlineHelpText>
    <label>Child Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Field_to_Aggregate__c.field-meta.xml
<CustomField>
    <fullName>Field_to_Aggregate__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the field used in the batch process to calculate the rollup criteria. Currently, only Id for a count of child object records is supported with future releases expected to include sum or other functions for calculations of field values on child object records. Default and only currently permitted value for record count operation is: Id</inlineHelpText>
    <label>Field to Aggregate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>Value is the API name of the custom rating object specified in Global Settings the the primary batch process is updating the values and applying the rating per the logic specified in that custom settings. Can be a single standard or custom object. i.e. Account or Project__c</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the API name of the field on the child object that is the standard or custom lookup or master-detail field relating it to the parent object. i.e. AccountId or Account__c</inlineHelpText>
    <label>Relationship Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Rollup_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Rollup_Criteria__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the SOQL query value limiting child object records used in the batch process to calculate the count of child object records to Rollup to the Aggregate Result Field. Use API Names of the field and the appropriate logical operators. i.e. CreatedDate = LAST_N_DAYS:90</inlineHelpText>
    <label>Rollup Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/CustomRating_Global_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Global Setting</label>
</CustomObject>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Custom_Rating_1_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Custom_Rating_1_Percentage__c</fullName>
    <inlineHelpText>This percentage will be applied to identify the Rating 1 records.</inlineHelpText>
    <label>Custom Rating 1 Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Custom_Rating_2_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Custom_Rating_2_Percentage__c</fullName>
    <inlineHelpText>This percentage will be applied to identify the Rating 2 records.</inlineHelpText>
    <label>Custom Rating 2 Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Custom_Rating_3_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Custom_Rating_3_Percentage__c</fullName>
    <inlineHelpText>This percentage will be applied to identify the Rating 3 records.</inlineHelpText>
    <label>Custom Rating 3 Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Custom_Rating_field__c.field-meta.xml
<CustomField>
    <fullName>Custom_Rating_Field__c</fullName>
    <inlineHelpText>This field will hold the values of actual ranking results</inlineHelpText>
    <label>Custom Rating Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Custom_Rating_Group_Field__c.field-meta.xml
<CustomField>
    <fullName>Custom_Rating_Group_Field__c</fullName>
    <inlineHelpText>This field is the criteria based on which custom rating is determined.</inlineHelpText>
    <label>Custom Rating Group Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Mention the object name on which you want to calculate the custom rating.</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Rating_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Rating_Criteria__c</fullName>
    <inlineHelpText>This field is where you enter your criteria using field API names and the conditions that will be used with them. This field uses SOQL formatting so your criteria string must be formatted like that. An example of how this might look is
E.g. Type !=&apos;Prospect&apos; AND RecordType.Name =&apos;Customer&apos;</inlineHelpText>
    <label>Rating Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Rating_Rollup_Sort_Order_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Rating_Rollup_Sort_Order_Criteria__c</fullName>
    <inlineHelpText>Mention here the ORDER BY portion of the Custom Rating to apply a sorting order for records on the Target Object. E.g. AnnualRevenue Desc, CreatedDate Desc</inlineHelpText>
    <label>Rating Rollup Sort Order Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Rating_Value_1__c.field-meta.xml
<CustomField>
    <fullName>Rating_Value_1__c</fullName>
    <inlineHelpText>Mention the actual value to be assigned for Rating 1</inlineHelpText>
    <label>Rating Value 1</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Rating_Value_2__c.field-meta.xml
<CustomField>
    <fullName>Rating_Value_2__c</fullName>
    <inlineHelpText>Mention the actual value to be assigned for Rating 2</inlineHelpText>
    <label>Rating Value 2</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Rating_Value_3__c.field-meta.xml
<CustomField>
    <fullName>Rating_Value_3__c</fullName>
    <inlineHelpText>Mention the actual value to be assigned for Rating 3</inlineHelpText>
    <label>Rating Value 3</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Use_RollupBatch_for_Rollup_Field__c.field-meta.xml
<CustomField>
    <fullName>Use_RollupBatch_for_Rollup_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Make this field True to use other custom settings or False to use the values in the rating rollup field.</inlineHelpText>
    <label>Use RollupBatch for Rollup Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomRating_TestDataFactory.cls
/**********************************************************************************************************
* Class Name: CustomRating_TestDataFactory
* Author: KGS
*
* ============================================================================================================
* ============================================================================================================
* Purpose: This class generates/insert an sObject with all the required fields.
* ============================================================================================================
* ============================================================================================================
* History:
* VERSION     DATE                  INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0         08-November-2021      KGS           Initial Development
***********************************************************************************************************/
public class CustomRating_TestDataFactory {
    
    public static CustomRating_Global_Setting__c createCustomRatingGlobalSetting() {
        
        CustomRating_Global_Setting__c globalSettingObj =  new CustomRating_Global_Setting__c();
        globalSettingObj.Object_Name__c = 'Account';
        globalSettingObj.Custom_Rating_Group_Field__c = 'Rating';
        globalSettingObj.Custom_Rating_1_Percentage__c=25;
        globalSettingObj.Custom_Rating_2_Percentage__c=25;
        globalSettingObj.Custom_Rating_3_Percentage__c=50;
        globalSettingObj.Custom_Rating_Field__c='Description';  
        globalSettingObj.Rating_Rollup_Sort_Order_Criteria__c = ' NumberOfEmployees Desc,CreatedDate Desc';
        globalSettingObj.Rating_Value_1__c='Hot';
        globalSettingObj.Rating_Value_2__c='Warm';
        globalSettingObj.Rating_Value_3__c='Cold';
        globalSettingObj.Rating_Criteria__c = 'Rating != null';
        globalSettingObj.Use_RollupBatch_for_Rollup_Field__c = true;         
        return globalSettingObj; 
    }
    
    public static Custom_Rating_Rollup_Batch_Settings__c createCustomRatingGlobalBatchSetting(){
        Custom_Rating_Rollup_Batch_Settings__c batchObj = new Custom_Rating_Rollup_Batch_Settings__c();
        batchObj.Aggregate_Result_Field__c = 'NumberOfEmployees';
        batchObj.Child_Object__c = 'Contact';
        batchObj.Rollup_Criteria__c = 'CreatedDate = LAST_N_DAYS:90';
        batchObj.Field_to_Aggregate__c = 'Id';
        batchObj.Parent_Object__c = 'Account';
        batchObj.Relationship_Field__c = 'AccountId';
        return batchObj;
    }    
    
    public static List<Account> createHotRatingAccount() {
        List<Account> accList = new List<Account>();
        for(Integer i=0 ; i< 12;i++){
            Account acc = new Account();
            acc.Name = 'Test Account' + i;
            acc.Rating = 'Hot';
            accList.add(acc);
        }
        return accList;
    }
    
    public static List<Account> createColdRatingAccount() {
        List<Account> accList = new List<Account>();
        for(Integer i=0 ; i< 12;i++){
            Account acc = new Account();
            acc.Name = 'Test Account' + i;
            acc.Rating = 'Cold';
            accList.add(acc);
        }
        return accList;
    }
    
    public static List<Contact> createContact(List<Account> accList){
        List<Contact> conList = new List<Contact>();
        for(Account acc :accList){
            Contact con = new Contact();
            con.LastName = 'Test Contact' + acc.Name;
            con.AccountId = acc.Id;
            conList.add(con);
        }        
        return conList; 
    }
    
}