force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/Custom_Rating_Rollup_Batch_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Rollup Batch Settings</label>
</CustomObject>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the API name of the object where Rollup values are pulled from. Can also be the same as the Parent Object or another standard or custom object related to the Parent Object. i.e. Opportunity or Project__c</inlineHelpText>
    <label>Child Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>Value is the API name of the custom rating object specified in Global Settings the the primary batch process is updating the values and applying the rating per the logic specified in that custom settings. Can be a single standard or custom object. i.e. Account or Project__c</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the API name of the field on the child object that is the standard or custom lookup or master-detail field relating it to the parent object. i.e. AccountId or Account__c</inlineHelpText>
    <label>Relationship Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Rollup_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Rollup_Criteria__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the SOQL query value limiting child object records used in the batch process to calculate the count of child object records to Rollup to the Aggregate Result Field. Use API Names of the field and the appropriate logical operators. i.e. CreatedDate = LAST_N_DAYS:90</inlineHelpText>
    <label>Rollup Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/CustomRating_Global_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Global Setting</label>
</CustomObject>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Custom_Rating_Group_Field__c.field-meta.xml
<CustomField>
    <fullName>Custom_Rating_Group_Field__c</fullName>
    <inlineHelpText>This field is the criteria based on which custom rating is determined.</inlineHelpText>
    <label>Custom Rating Group Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Mention the object name on which you want to calculate the custom rating.</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Rating_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Rating_Criteria__c</fullName>
    <inlineHelpText>This field is where you enter your criteria using field API names and the conditions that will be used with them. This field uses SOQL formatting so your criteria string must be formatted like that. An example of how this might look is
E.g. Type !=&apos;Prospect&apos; AND RecordType.Name =&apos;Customer&apos;</inlineHelpText>
    <label>Rating Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomRating_Utility.cls
/**********************************************************************************************************
* Class Name: CustomRating_Utility
* Author: KGS
*
* ============================================================================================================
* ============================================================================================================
* Purpose: This class contains generic methods which are used for CustomRating batch classes.
* ============================================================================================================
* ============================================================================================================
* History:
* VERSION     DATE                  INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0         01-November-2021      KGS           Initial Development
***********************************************************************************************************/
public class CustomRating_Utility {
    
    public static final String SELECT_STR = 'SELECT Id, ';
    public static final String SELECT_COUNT_STR = 'SELECT count(Id)';
    public static final String FROM_STR = ' FROM ';
    public static final String WHERE_STR= ' WHERE ';
    public static final String ORDER_BY_STR= ' ORDER BY ';
    public static final String CreatedDate_Desc_STR=',CreatedDate Desc';
    public static final String GROUP_BY_STR = ' GROUP BY ';
    
    
    public static CustomRating_Global_Setting__c getCustomRatingGlobalSetting(){
        CustomRating_Global_Setting__c globalSettingObj = CustomRating_Global_Setting__c.getInstance();
        return globalSettingObj;
    }
    
    // This method counts the total number of records which satisfies the criteria.
    public static List<AggregateResult> fetchSobjectCount(CustomRating_Global_Setting__c globalSettingObj,String ratingField){        
        String query = SELECT_COUNT_STR + FROM_STR;
        query += globalSettingObj.Object_Name__c + WHERE_STR;
        query += globalSettingObj.Custom_Rating_Group_Field__c + ' = ' + '\''+ratingField+'\'';
        if(globalSettingObj.Rating_Criteria__c != null){
            query += ' AND ' + globalSettingObj.Rating_Criteria__c;
        } 
        System.debug('query==>'+query);
        List<AggregateResult> aggregateResultList = Database.query(query);        
        return aggregateResultList;
    }
    
    // Calculate count of records based on percentage
    public static Integer calculateRatingCounts(Integer listSize,Decimal tierPercentage){
        Decimal ratingValue = Double.valueOf(listSize * tierPercentage)/100;
        Integer ratingCount = ratingValue.round(System.RoundingMode.UP).intValue();        
        return ratingCount;
    }
    
    // Fetch the group field values
    public static List<String> getGroupFieldValues(){
        CustomRating_Global_Setting__c globalSettingObj = getCustomRatingGlobalSetting();        
        List<String> pickListValuesList= new List<String>();
        try{
            String strObjectName = globalSettingObj.Object_Name__c;
            String strPicklistField = globalSettingObj.Custom_Rating_Group_Field__c;            
            Map<String, String> mapPickListValues = new Map<String, String>();
            Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(strObjectName);
            Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
            Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
            List<Schema.PicklistEntry> lstPickListValues = mapFields.get(strPicklistField).getDescribe().getPickListValues();
            for (Schema.PicklistEntry objPickList : lstPickListValues) {
                pickListValuesList.add(objPickList.getValue());
            }
        }Catch(Exception e){
            System.debug('exception==>'+e.getMessage());
        }
        
        return pickListValuesList;
    }
    
    // Get the child relationship name based on parent object and child object name.
    public static string getChildRelationshipName(Custom_Rating_Rollup_Batch_Settings__c customRatingSetting){
        String parentObject = customRatingSetting.Parent_Object__c;
        String childObject = customRatingSetting.Child_Object__c;
        String childRelationshipName;
        
        Schema.SObjectType parentSobjectType = Schema.getGlobalDescribe().get(parentObject);
        Schema.SObjectType childSobjectType = Schema.getGlobalDescribe().get(childObject);
        
        Schema.DescribeSObjectResult objDescribeSobject = parentSobjectType.getDescribe();
        for (ChildRelationship relation : objDescribeSobject.getChildRelationships()){
            if (relation.getChildSObject() == childSobjectType){
                String relationShipFieldName = string.valueof(relation.getField());
                if(customRatingSetting.Relationship_Field__c.equals(relationShipFieldName)){
                    childRelationshipName = relation.getRelationshipName();
                }                
            }
        }
        return childRelationshipName;
    }    
    
    // This method fetches the count of child object with parent Id.
    public static List<AggregateResult> fetchChildObjectCounts(Custom_Rating_Rollup_Batch_Settings__c customRatingSetting,Set<String> parentIdSet){
        
        String query = SELECT_COUNT_STR + ', ';
        query += customRatingSetting.Relationship_Field__c;
        query += FROM_STR + customRatingSetting.Child_Object__c;
        query += WHERE_STR + customRatingSetting.Relationship_Field__c + ' IN ';
        query += ':parentIdSet ';
        if(customRatingSetting.Rollup_Criteria__c !=null){
            query += ' AND ';
            query += customRatingSetting.Rollup_Criteria__c + ' ';
        }
        
        query +=  GROUP_BY_STR + customRatingSetting.Relationship_Field__c;
        
        System.debug('query==>'+query);
        List<AggregateResult> aggregateResultList = Database.query(query);        
        return aggregateResultList;
    }
}