force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/Custom_Rating_Rollup_Batch_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Rollup Batch Settings</label>
</CustomObject>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the API name of the object where Rollup values are pulled from. Can also be the same as the Parent Object or another standard or custom object related to the Parent Object. i.e. Opportunity or Project__c</inlineHelpText>
    <label>Child Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>Value is the API name of the custom rating object specified in Global Settings the the primary batch process is updating the values and applying the rating per the logic specified in that custom settings. Can be a single standard or custom object. i.e. Account or Project__c</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Rating_Rollup_Batch_Settings__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <inlineHelpText>This value is required if the rollup batch is active and is the API name of the field on the child object that is the standard or custom lookup or master-detail field relating it to the parent object. i.e. AccountId or Account__c</inlineHelpText>
    <label>Relationship Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/CustomRating_Global_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Rating Global Setting</label>
</CustomObject>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Custom_Rating_Group_Field__c.field-meta.xml
<CustomField>
    <fullName>Custom_Rating_Group_Field__c</fullName>
    <inlineHelpText>This field is the criteria based on which custom rating is determined.</inlineHelpText>
    <label>Custom Rating Group Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Mention the object name on which you want to calculate the custom rating.</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRating_Global_Setting__c/fields/Rating_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Rating_Criteria__c</fullName>
    <inlineHelpText>This field is where you enter your criteria using field API names and the conditions that will be used with them. This field uses SOQL formatting so your criteria string must be formatted like that. An example of how this might look is
E.g. Type !=&apos;Prospect&apos; AND RecordType.Name =&apos;Customer&apos;</inlineHelpText>
    <label>Rating Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomRating_UtilityTest.cls
/**********************************************************************************************************
* Class Name: CustomRating_UtilityTest
* Author: KGS
*
* ============================================================================================================
* ============================================================================================================
* Purpose: Test class to test the functionality for 'CustomRating_Utility' apex class.
* ============================================================================================================
* ============================================================================================================
* History:
* VERSION     DATE                  INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0         01-November-2021      KGS           Initial Development
***********************************************************************************************************/
@isTest
public class CustomRating_UtilityTest {
	@testSetup 
    public static void setup(){        
        //Creating "CustomRating Global Setting" object
        CustomRating_Global_Setting__c CRGScOne = CustomRating_TestDataFactory.createCustomRatingGlobalSetting();
        insert CRGScOne;
        
        Custom_Rating_Rollup_Batch_Settings__c batchObj = CustomRating_TestDataFactory.createCustomRatingGlobalBatchSetting();
        insert batchObj;
        
         //Creating "Account" object
        List<Account> accountHotRatingList = CustomRating_TestDataFactory.createHotRatingAccount(); 
        insert accountHotRatingList; 
        
        List<Contact> conList = CustomRating_TestDataFactory.createContact(accountHotRatingList);
        insert conList;
    }
    
    @isTest
    Public static void fetchSobjectCountTest(){
        CustomRating_Global_Setting__c globalSetting = [Select Id,
                                                        Object_Name__c,
                                                        Custom_Rating_Group_Field__c,
                                                        Rating_Criteria__c
                                                        From CustomRating_Global_Setting__c Limit 1];
        Test.startTest();
        List<AggregateResult> sObjList = CustomRating_Utility.fetchSobjectCount(globalSetting,'Hot');  
        Test.stopTest(); 
        
        Integer listSize = Integer.valueOf(sObjList[0].get('expr0'));
        System.assert(listSize !=0);
    }
    
    @isTest
    Public static void getCustomRatingGlobalSettingTest(){
        Test.startTest();
        CustomRating_Utility.getCustomRatingGlobalSetting();
        Test.stopTest(); 
    }
    
    @isTest
    Public static void calculateRatingCountsTest(){
        Integer count;
        Test.startTest();
        count = CustomRating_Utility.calculateRatingCounts(3, 25);
        Test.stopTest(); 
        System.assert(count !=0);
    }
    
    @isTest
    Public static void getGroupFieldValuesTest(){
        List<String> pickListValuesList = new List<String>();
        Test.startTest();
        pickListValuesList = CustomRating_Utility.getGroupFieldValues();
        Test.stopTest(); 
        System.assert(!pickListValuesList.isEmpty());
    }
    
    @isTest
    Public static void getChildRelationshipNameTest(){
        String childRelationshipName;
        Custom_Rating_Rollup_Batch_Settings__c globalBatchSetting = [Select Id,
                                                                     Parent_Object__c,
                                                                     Child_Object__c,
                                                                     Relationship_Field__c
                                                                     From Custom_Rating_Rollup_Batch_Settings__c 
                                                                     Limit 1];
        Test.startTest();
        childRelationshipName = CustomRating_Utility.getChildRelationshipName(globalBatchSetting);
        Test.stopTest(); 
        System.assertEquals('Contacts', childRelationshipName);
    }
}